# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 18:49
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20160813_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='coordinates',
            field=jsonfield.fields.JSONField(),
        ),
    ]
